apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: demo.yaml
spec:
  flows:
    - route:
        from:
          uri: kamelet:timer-source
          steps:
            - setBody:
                expression:
                  groovy:
                    expression: '[status: 200, body: ''abcdef-ankur'']'
            - marshal:
                json:
                  library: jackson
            - log:
                message: ${body}
          parameters:
            period: 66666
            message: Hello World Demo
        id: routeX
