apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: hack
spec:
  flows:
    - route:
        from:
          uri: kamelet:http-source
          steps:
            - transform:
                expression:
                  mvel:
                    expression: ${data}+"nirav"
                    trim: true
            - log:
                message: ${data}
          parameters:
            url: https://api.exchange.coinbase.com/products
