apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: hack
spec:
  flows:
    - route:
        from:
          uri: kamelet:http-source
          steps:
#             - to:
#                 uri: file:/scripts/
#                 parameters:
#                   fileName: demoFile
            - log:
                message: nirav
          parameters:
            url: https://api.exchange.coinbase.com/products
