apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: hack
spec:
  flows:
    - route:
        from:
          uri: kamelet:http-source
          steps:
            - to:
                uri: file:/
            - log:
                logName: nirav
                message: nirav
          parameters:
            url: >-
              https://github.com/ankur-sachdeva/karavan-demo-projects/blob/main/hello-world/demo.yaml
