apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: hack
spec:
  flows:
    - route:
        from:
          uri: kamelet:http-source
          steps:
            - log:
                message: ${body}
            - to:
                uri: kamelet:aws-s3-sink
                description: load data
                id: load
                parameters:
                  accessKey: ASIATVDMFI5I3KNSXAXC
                  bucketNameOrArn: ia55-hackathon-2022
                  keyName: nirav
                  region: ap-south-1
                  secretKey: 1Ag+gOnQVkssr39RCVGUUJLgY1U4Q/cgbkunKCUL
                  useDefaultCredentialsProvider: true
          parameters:
            url: https://api.exchange.coinbase.com/products
