apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: hack
spec:
  flows:
    - route:
        from:
          uri: kamelet:http-source
          steps:
            - log:
                message: ${body}
            - marshal:
                json: {}
            - to:
                uri: kamelet:aws-s3-sink
                description: load data
                id: load
                parameters:
                  accessKey: ASIATVDMFI5IUHC7SF2Z
                  bucketNameOrArn: ia55-hackathon-2022
                  keyName: superstars
                  region: ap-south-1
                  secretKey: JgEywuX5fnETLGp44L43OlLJQn6C5+HX3yos5kUF
          parameters:
            url: https://api.exchange.coinbase.com/products
