apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: CryptoIngestor
spec:
  flows:
    - route:
        from:
          uri: kamelet:http-secured-source
          steps:
            - unmarshal:
                json: {}
            - marshal:
                csv: {}
          parameters:
            url: https://api.exchange.coinbase.com/products
