apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: hack
spec:
  flows:
    - route:
        from:
          uri: kamelet:http-source
          steps:
            - log:
                message: ${body}
          parameters:
            url: https://api.exchange.coinbase.com/products
